console.log("Script Load");
(function($) {
    $(document).ready(function() {
        console.log('jQuery Ready');
        var $_0 = $('li._0');
        var $_1 = $('li._1');
        var $_2 = $('li._2');
        var $_3 = $('li._3');
        var $_4 = $('li._4');
        var $_5 = $('li._5');
        var $_6 = $('li._6');
        var $_7 = $('li._7');

        $_0.on('click',function(){
            console.log('클릭했수다');
            $_0.css('transform', 'translateY(270px)');
            $_0.css('transition-delay', '0.8s');
            $_1.css('opacity', '0');
            $_2.css('opacity', '0');
            $_3.css('opacity', '0');
            $_4.css('opacity', '0');
            $_5.css('opacity', '0');
            $_6.css('opacity', '0');
            $_7.css('opacity', '0');
            setTimeout(function(){
                $_1.css('transform', 'translateX(10000px)');
                $_2.css('transform', 'translateX(10000px)');
                $_3.css('transform', 'translateX(10000px)');
                $_4.css('transform', 'translateX(10000px)');
                $_5.css('transform', 'translateX(10000px)');
                $_6.css('transform', 'translateX(10000px)');
                $_7.css('transform', 'translateX(10000px)');
                // $_3.remove();
                // $_4.remove();
            },1000);
            $('.nav').append('<div class="_line"></div>');
            // $('.nav').append('<a href="../html/MemoriesOfMatsuko.html"><div class="_line2"></div></a>');
            $('title').append('<meta http-equiv="refresh" content="2; url=../html/NightPicnic.html">');
        });
        $_1.on('click',function(){
            console.log('클릭했수다');
            $_1.css('transform', 'translateY(-20px)');
            $_1.css('transition-delay', '0.8s');
            $_0.css('opacity', '0');
            $_2.css('opacity', '0');
            $_3.css('opacity', '0');
            $_4.css('opacity', '0');
            $_5.css('opacity', '0');
            $_6.css('opacity', '0');
            $_7.css('opacity', '0');
            setTimeout(function(){
                $_0.css('transform', 'translateX(10000px)');
                $_2.css('transform', 'translateX(10000px)');
                $_3.css('transform', 'translateX(10000px)');
                $_4.css('transform', 'translateX(10000px)');
                $_5.css('transform', 'translateX(10000px)');
                $_6.css('transform', 'translateX(10000px)');
                $_7.css('transform', 'translateX(10000px)');
                // $_3.remove();
                // $_4.remove();
            },1000);
            $('.nav').append('<div class="_line"></div>');
            // $('.nav').append('<a href="../html/MemoriesOfMatsuko.html"><div class="_line2"></div></a>');
            $('title').append('<meta http-equiv="refresh" content="2; url=../html/MemoriesOfMatsuko.html">');
        });
        $_2.on('click',function(){
            console.log('클릭했수다2');
            $_2.css('transform', 'translateY(130px)');
            $_2.css('transition-delay', '0.8s');
            $_0.css('opacity', '0');
            $_1.css('opacity', '0');
            $_3.css('opacity', '0');
            $_4.css('opacity', '0');
            $_5.css('opacity', '0');
            $_6.css('opacity', '0');
            $_7.css('opacity', '0');
            setTimeout(function(){
                $_0.css('transform', 'translateX(10000px)');
                $_1.css('transform', 'translateX(10000px)');
                $_3.css('transform', 'translateX(10000px)');
                $_4.css('transform', 'translateX(10000px)');
                $_5.css('transform', 'translateX(10000px)');
                $_6.css('transform', 'translateX(10000px)');
                $_7.css('transform', 'translateX(10000px)');
                // $_3.remove();
                // $_4.remove();
            },1000);
            $('.nav').append('<div class="_line"></div>');
            // $('.nav').append('<a href="../html/Moonassi.html"><div class="_line2"></div></a>');
            $('title').append('<meta http-equiv="refresh" content="2; url=../html/Moonassi.html">');
        });
        $_3.on('click',function(){
            console.log('클릭했수다');
            $_3.css('transform', 'translateY(-120px)');
            $_3.css('transition-delay', '0.8s');
            $_0.css('opacity', '0');
            $_2.css('opacity', '0');
            $_1.css('opacity', '0');
            $_4.css('opacity', '0');
            $_5.css('opacity', '0');
            $_6.css('opacity', '0');
            $_7.css('opacity', '0');
            setTimeout(function(){
                $_0.css('transform', 'translateX(10000px)');
                $_2.css('transform', 'translateX(10000px)');
                $_1.css('transform', 'translateX(10000px)');
                $_4.css('transform', 'translateX(10000px)');
                $_5.css('transform', 'translateX(10000px)');
                $_6.css('transform', 'translateX(10000px)');
                $_7.css('transform', 'translateX(10000px)');
                // $_3.remove();
                // $_4.remove();
            },1000);
            $('.nav').append('<div class="_line"></div>');
            // $('.nav').append('<a href="../html/Takkoyakki.html"><div class="_line2"></div></a>');
            $('title').append('<meta http-equiv="refresh" content="2; url=../html/Takkoyakki.html">');
        });
        $_4.on('click',function(){
            console.log('클릭했수다');
            $_4.css('transform', 'translateY(-200px)');
            $_4.css('transition-delay', '0.8s');
            $_0.css('opacity', '0');
            $_2.css('opacity', '0');
            $_3.css('opacity', '0');
            $_1.css('opacity', '0');
            $_5.css('opacity', '0');
            $_6.css('opacity', '0');
            $_7.css('opacity', '0');
            setTimeout(function(){
                $_0.css('transform', 'translateX(10000px)');
                $_2.css('transform', 'translateX(10000px)');
                $_3.css('transform', 'translateX(10000px)');
                $_1.css('transform', 'translateX(10000px)');
                $_5.css('transform', 'translateX(10000px)');
                $_6.css('transform', 'translateX(10000px)');
                $_7.css('transform', 'translateX(10000px)');
                // $_3.remove();
                // $_4.remove();
            },1000);
            $('.nav').append('<div class="_line"></div>');
            // $('.nav').append('<a href="../html/WhatYum.html"><div class="_line2"></div></a>');
            $('title').append('<meta http-equiv="refresh" content="2; url=../html/WhatYum.html">');
        });
        $_5.on('click',function(){
            console.log('클릭했수다');
            $_5.css('transform', 'translateY(70px)');
            $_5.css('transition-delay', '0.8s');
            $_0.css('opacity', '0');
            $_2.css('opacity', '0');
            $_3.css('opacity', '0');
            $_1.css('opacity', '0');
            $_4.css('opacity', '0');
            $_6.css('opacity', '0');
            $_7.css('opacity', '0');
            setTimeout(function(){
                $_0.css('transform', 'translateX(10000px)');
                $_2.css('transform', 'translateX(10000px)');
                $_3.css('transform', 'translateX(10000px)');
                $_1.css('transform', 'translateX(10000px)');
                $_4.css('transform', 'translateX(10000px)');
                $_6.css('transform', 'translateX(10000px)');
                $_7.css('transform', 'translateX(10000px)');
                // $_3.remove();
                // $_4.remove();
            },1000);
            $('.nav').append('<div class="_line"></div>');
            // $('.nav').append('<a href="../html/WhatYum.html"><div class="_line2"></div></a>');
            $('title').append('<meta http-equiv="refresh" content="2; url=../html/NightOff.html">');
        });
        $_6.on('click',function(){
            console.log('클릭했수다');
            $_6.css('transform', 'translateY(190px)');
            $_6.css('transition-delay', '0.8s');
            $_0.css('opacity', '0');
            $_2.css('opacity', '0');
            $_3.css('opacity', '0');
            $_1.css('opacity', '0');
            $_5.css('opacity', '0');
            $_4.css('opacity', '0');
            $_7.css('opacity', '0');
            setTimeout(function(){
                $_0.css('transform', 'translateX(10000px)');
                $_2.css('transform', 'translateX(10000px)');
                $_3.css('transform', 'translateX(10000px)');
                $_1.css('transform', 'translateX(10000px)');
                $_5.css('transform', 'translateX(10000px)');
                $_4.css('transform', 'translateX(10000px)');
                $_7.css('transform', 'translateX(10000px)');
                // $_3.remove();
                // $_4.remove();
            },1000);
            $('.nav').append('<div class="_line"></div>');
            // $('.nav').append('<a href="../html/WhatYum.html"><div class="_line2"></div></a>');
            $('title').append('<meta http-equiv="refresh" content="2; url=../html/Momentrip.html">');
        });
        $_7.on('click',function(){
            console.log('클릭했수다');
            $_7.css('transform', 'translateY(-260px)');
            $_7.css('transition-delay', '0.8s');
            $_0.css('opacity', '0');
            $_2.css('opacity', '0');
            $_3.css('opacity', '0');
            $_1.css('opacity', '0');
            $_5.css('opacity', '0');
            $_4.css('opacity', '0');
            $_6.css('opacity', '0');
            setTimeout(function(){
                $_0.css('transform', 'translateX(10000px)');
                $_2.css('transform', 'translateX(10000px)');
                $_3.css('transform', 'translateX(10000px)');
                $_1.css('transform', 'translateX(10000px)');
                $_5.css('transform', 'translateX(10000px)');
                $_4.css('transform', 'translateX(10000px)');
                $_6.css('transform', 'translateX(10000px)');
                // $_3.remove();
                // $_4.remove();
            },1000);
            $('.nav').append('<div class="_line"></div>');
            // $('.nav').append('<a href="../html/WhatYum.html"><div class="_line2"></div></a>');
            $('title').append('<meta http-equiv="refresh" content="2; url=../html/Stalker.html">');
        });
    });
})(jQuery);